export const GET_STUDENTS = 'GET_STUDENTS';
export const ADD_STUDENT = 'ADD_STUDENT';
export const EDIT_STUDENT = 'EDIT_STUDENT';
export const GET_EDIT_STUDENT_DETAILS = 'GET_EDIT_STUDENT_DETAILS';
export const DELETE_STUDENT = 'DELETE_STUDENT';
